import { Button, VerticalBox, AboutSlint } from "std-widgets.slint";



export component AboutPage inherits VerticalBox {

    AboutSlint { }

    Text {
        text: "Rust Crates Used in This Application:";
        font-weight: 700;
        font-size: 16px;
        horizontal-alignment: center;
        padding-top: 20px;
    }

    Text {
        text: "• Slint - UI Framework\n• DuckDB - Data backend\n• Native Dialog - File Selector & Dialog Box\n• Clap - Command Line Arguments\n• Anyhow - Error Handling\n• Chrono - Date/Time Parsing\n• Base64 - Binary to Base64 Conversion\n• Tokio - Asynchronous Runtime";
        horizontal-alignment: center;
        padding-top: 10px;
        padding-bottom: 20px;
    }

    Rectangle { 
        max-height: 10px;
    }

    Text {
        text: "GitHub: https://github.com/cbritton/slint_duckdb_viewer";
        font-weight: 700;
        font-size: 14px;
        horizontal-alignment: center;
        padding-top: 20px;
    }

    // Spacer
    Rectangle { }
}
